### ISSUE TITLE
Checking for IE8/9 not robust enough

### ISSUE THREAD

**Issue by constantm** [mapbox/corslite#14]
Corslite checks whether we are on IE by looking for `withCredentials` on the XMLHttpRequest object. Some mocking libraries (notably [Pretender](https://github.com/pretenderjs/pretender)) breaks since it doesn't always have the `withCredentials` property on the XMLHttpRequest object.

**Comment by constantm** [comment]
Fixed by [this PR](https://github.com/mapbox/corslite/pull/15)

**Comment by tmcw** [comment]
I'm divided on whether to merge this. I'd like to see [if Pretender has a response to the incompatibility](https://github.com/pretenderjs/pretender/issues/112): it's been a long-followed rule that libraries should not override globals.

**Comment by jfirebaugh** [comment]
I'm going to close #15 -- it essentials undoes #9, and would result in corslite using XDomainRequest rather than XMLHttpRequest on IE10 always and on IE11 in non-Edge mode.

The `withCredentials` check is the [widely accepted means of feature-detecting CORS support](http://stackoverflow.com/questions/1641507/detect-browser-support-for-cross-domain-xmlhttprequests). I really think this should be fixed in Pretender.

**Comment by constantm** [comment]
Aaah okay cool. That makes perfect sense. I wasn't aware that using `withCredentials` is used that much. :) Let's see what we can do on the Pretender side!
